### PR TITLE
OpenSSF Badge Score

### PR DESCRIPTION
**Pull request by Salkimmich**
This widget will provide an up-to-date score for your OpenSSSF Badge compliance. To get to 100%, there are 3 sections of this need maintainer review. The links below are from you repository report: 

1. Confirm [Cryptographic Best Practices](https://www.bestpractices.dev/en/projects/8914#security)
2. Confirm [Static and Dynamic Analysis Tooling ](https://www.bestpractices.dev/en/projects/8914#analysis)

### CODE REVIEW

**Comment by joergroedel** [comment]
Hey @Salkimmich, Thanks for your contribution and setting up OpenSSF checking. CI is failing currently failing on this PR, can you please sign-off the commit and add a sentence or two as commit message? Thanks!

**Comment by joergroedel** [comment]
> This widget will provide an up-to-date score for your OpenSSSF Badge compliance. To get to 100%, there are 3 sections of this need maintainer review. The links below are from you repository report:
> 
> 1. Confirm [Cryptographic Best Practices](https://www.bestpractices.dev/en/projects/8914#security)
> 2. Confirm [Static and Dynamic Analysis Tooling ](https://www.bestpractices.dev/en/projects/8914#analysis)

I updated the remaining questions about cryptography and code analysis. The badge now shows passing.

**Comment by Salkimmich** [comment]
H

**Review by Salkimmich — COMMENTED** [review]
OpenSSF Badge Widget added to Read.me

**Comment by joergroedel** [comment]
Hi Sal,

> OpenSSF Badge Widget added to Read.me

Thanks for the update. Can you also please make the CI succeed so I can merge your commit? The Signed-off-by and a short commit message is missing.

Thanks!

**Pull request merged**
