### PR TITLE
docs: add owner of ApicEmul item

### PR DESCRIPTION
**Pull request by vijaydhanraj**
- Add myself as the owner of the ApicEmul item, to add vXAPIC and vX2APIC support for TD partitioned guest.

@msft-jlange Please let me know if you plan to work on this item and we can co-own this item.

### CODE REVIEW

**Comment by msft-jlange** [comment]
> * Add myself as the owner of the ApicEmul item, to add vXAPIC and vX2APIC support for guest OS.
> @msft-jlange Please let me know if you plan to work on this item and we can co-own this item.

I don't know what "owner" is supposed to mean, but I am doing active development in this area and will continue to do so.  We should coordinate if you want to be involved too.

**Comment by vijaydhanraj** [comment]
Owners are people assigned for a particular task/sub-task in the development plan. 
Yes, sure I would like to be involved as well. Please let me know how we can get started.

Currently I am following your PRs on this and seeing if I can apply/extend it to TD partitioning.

**Comment by joergroedel** [comment]
Hi Vijay, some of the CI checks failed, please add a message body to all commits to make the tests pass.

**Comment by vijaydhanraj** [comment]
Hi Joerg, I have added the body and also updated the commit to add @msft-jlange as owner. Please let me know if anything else is needed. Thx.

**Pull request merged**
