### PR TITLE
acpi/tables: fix undefined behavior due to pointer misalignment

### PR DESCRIPTION
**Pull request by 00xc**
Fix an undefined behavior that would occur when the alignment requirements for `core::slice::from_raw_parts()` would not be held. The pointer passed to this function must be aligned so that each member of the slice is itself aligned, which could not be guaranteed.

Instead of creating a new slice of u32's, iterate over the individual bytes in chunks of 4 and parse each u32 individually.

Fixes: #115
Fixes: 62f5c6fe "acpi: return ACPITable content as byte slice instead of raw pointer"

### CODE REVIEW

**Comment by joergroedel** [comment]
This fails to boot here with

```
[SVSM] ERROR: Panic: CPU[0] panicked at 'Failed to load ACPI tables: Acpi', src/svsm.rs:435:44
[SVSM] ---BACKTRACE---:
[SVSM]   [0xffffff8000006101]
[SVSM] ---END---
```

**Comment by joergroedel** [comment]
Backtrace points to `svsm_main()`, so not very helpful.

**Comment by 00xc** [comment]
> This fails to boot here with
> 
> ```
> [SVSM] ERROR: Panic: CPU[0] panicked at 'Failed to load ACPI tables: Acpi', src/svsm.rs:435:44
> [SVSM] ---BACKTRACE---:
> [SVSM]   [0xffffff8000006101]
> [SVSM] ---END---
> ```

Had the wrong endianness for some reason, it should properly boot now.

**Comment by joergroedel** [comment]
Thanks, boots now.

**Pull request merged**
